# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9369ae9e594185dfaa0e6346dbbd5fa7636c95f5f1339974608f3b2d0c561e6b1cffea8ce614ba01229b46209b7c14d7f1225cf84bccec88f22670a28faeddb6

test:
  secret_key_base: f4d69d191310f6808477555534bb90629973fbcabd46d969629e8f68e9bb604a577e8faa817dfd81e3ac2c029c31bad694c4286a6b94d1421ce5ca7d456989b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
